live_config_reload = true

shell = "zsh"
# shell = { program = "pwsh", args = ["-nologo", "-WorkingDirectory", "~"] }
# shell = { program = "wsl", args = ["~", "tmux new-session -A -s main"] }

[env]
TERM = "xterm-256color"

[window]
decorations_theme_variant = "Dark"
dimensions = { lines = 24, columns = 80 }
position = { x = 420, y = 120 }
opacity = 1.0
dynamic_title = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 14

[colors]
transparent_background_colors = true

[colors.primary]
background = '#1E1E2E' # base
foreground = '#CDD6F4' # text
# Bright and dim foreground colors
dim_foreground = '#CDD6F4' # text
bright_foreground = '#CDD6F4' # text

# Cursor colors
[colors.cursor]
text = '#1E1E2E' # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#1E1E2E' # base
cursor = '#B4BEFE' # lavender

# Search colors
[colors.search.matches]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.search.focused_match]
foreground = '#1E1E2E' # base
background = '#A6E3A1' # green

[colors.footer_bar]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#1E1E2E' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Selection colors
[colors.selection]
text = '#1E1E2E' # base
background = '#F5E0DC' # rosewater

# Normal colors
[colors.normal]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1

# Bright colors
[colors.bright]
black = '#585B70' # surface2
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#A6ADC8' # subtext0

# Dim colors
[colors.dim]
black = '#45475A' # surface1
red = '#F38BA8' # red
green = '#A6E3A1' # green
yellow = '#F9E2AF' # yellow
blue = '#89B4FA' # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5' # teal
white = '#BAC2DE' # subtext1

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
{ key = "F11", mods = "None", action = "ToggleFullscreen" },
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "W", mods = "Control|Shift", action = "Quit" },
]
