import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

live_config_reload = true

shell = "zsh"
# shell = { program = "pwsh", args = ["-nologo", "-WorkingDirectory", "~"] }
# shell = { program = "wsl", args = ["~", "tmux new-session -A -s main"] }

[env]
TERM = "xterm-256color"

[window]
decorations_theme_variant = "Dark"
dimensions = { lines = 20, columns = 80 }
# position = { x = 420, y = 120 }
opacity = 0.95
# dynamic_title = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 16

[colors]
transparent_background_colors = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", mods = "Control", action = "Paste" }]

[keyboard]
bindings = [
  { key = "F11", mods = "None", action = "ToggleFullscreen" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "W", mods = "Control|Shift", action = "Quit" },
]
