# import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

live_config_reload = true

# shell = "zsh"
# shell = { program = "tmux", args = ["new-session", "-A", "-s", "main"] }
# shell = { program = "pwsh", args = ["-nologo", "-WorkingDirectory", "~"] }
# shell = { program = "wsl", args = ["~", "tmux new-session -A -s main"] }

[env]
TERM = "alacritty"

[window]
dynamic_padding = true
decorations_theme_variant = "Dark"
dimensions = { lines = 20, columns = 80 }
# position = { x = 420, y = 120 }
opacity = 0.90
dynamic_title = false

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
size = 18

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Right", action = "PasteSelection" }]

[keyboard]
bindings = [
  { key = "F11", mods = "None", action = "ToggleFullscreen" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "W", mods = "Control|Shift", action = "Quit" },
  { key = "X", mods = "Control|Shift", action = "Quit" },
]
