[colors]
foreground = "#e0def4"
background = "#232136"
cursor_bg = "#59546d"
cursor_border = "#59546d"
cursor_fg = "#e0def4"
selection_bg = "#393552"
selection_fg = "#817c9c"

ansi = [
  "#393552",
  "#eb6f92",
  "#3e8fb0",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ea9a97",
  "#e0def4",
]
brights = [
  "#6e6a86",
  "#eb6f92",
  "#3e8fb0",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ea9a97",
  "#e0def4",
]

[colors.tab_bar]
background = "#232136"
inactive_tab_edge = "#6e6a86"

[colors.tab_bar.active_tab]
fg_color = "#e0def4"
bg_color = "#393552"

[colors.tab_bar.inactive_tab]
fg_color = "#6e6a86"
bg_color = "#232136"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e0def4"
bg_color = "#393552"
# intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#6e6a86"
bg_color = "#232136"

[colors.tab_bar.new_tab_hover]
fg_color = "#e0def4"
bg_color = "#393552"
# intensity = "Bold"
